# Generated by Django 3.2.20 on 2024-02-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20240218_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
