# Generated by Django 3.2.10 on 2024-02-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcms', '0002_auto_20240211_0220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
