# Generated by Django 3.2.10 on 2024-02-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcms', '0005_auto_20240211_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
